from prometheus_client import Counter, Histogram

prices_collected_total = Counter(
    "mp_prices_collected_total",
    "Number of price records successfully collected",
    ["component", "source"],
)

scraper_errors_total = Counter(
    "mp_scraper_errors_total",
    "Number of scraper failures",
    ["scraper"],
)

forecast_generated_total = Counter(
    "mp_forecast_generated_total",
    "Number of forecasts generated by Prophet",
    ["component"],
)

anomalies_detected_total = Counter(
    "mp_anomalies_detected_total",
    "Number of anomalies detected above WARNING threshold",
    ["component", "severity"],
)

forecast_duration_seconds = Histogram(
    "mp_forecast_duration_seconds",
    "Time spent running Prophet forecast (CPU-bound)",
    ["component"],
    buckets=[0.5, 1.0, 2.0, 5.0, 10.0, 30.0, 60.0],
)
