from prometheus_client import Counter, Histogram

# --- HTTP metrics (populated by middleware in main.py) ---

http_requests_total = Counter(
    "http_requests_total",
    "Total HTTP requests",
    ["method", "path", "status_code"],
)

http_request_duration_seconds = Histogram(
    "http_request_duration_seconds",
    "HTTP request latency in seconds",
    ["method", "path"],
    buckets=[0.005, 0.01, 0.025, 0.05, 0.1, 0.25, 0.5, 1.0, 2.5, 5.0],
)

# --- Business metrics ---

prices_collected_total = Counter(
    "mp_prices_collected_total",
    "Number of price records successfully collected",
    ["component", "source"],
)

scraper_errors_total = Counter(
    "mp_scraper_errors_total",
    "Number of scraper failures",
    ["scraper"],
)

forecast_generated_total = Counter(
    "mp_forecast_generated_total",
    "Number of forecasts generated by Prophet",
    ["component"],
)

anomalies_detected_total = Counter(
    "mp_anomalies_detected_total",
    "Number of anomalies detected above WARNING threshold",
    ["component", "severity"],
)

forecast_duration_seconds = Histogram(
    "mp_forecast_duration_seconds",
    "Time spent running Prophet forecast (CPU-bound)",
    ["component"],
    buckets=[0.5, 1.0, 2.0, 5.0, 10.0, 30.0, 60.0],
)
